input-field {
    outer_color = rgba(33ccffee)
    inner_color = rgba(0,0,0, 0.0)
    size = 20%, 5%
    font_color = rgb(143,143,143)
    position = 0, -70
    halign = center
    valign = center
    fade_on_empty = false
  }
background {
    path = /home/jose/Pictures/Wallpapers/John_Martin_Le_Pandemonium_Louvre.JPG
    blur_passes = 2
  }
