#KITTY CONFIG

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

#Font configuration
font_family JetBrains Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13.0

# Window
#
placement_strategy center
